Feature/tag overview
scm-manager/scm-manager pull request #1331
Opened 2020-09-16 12:41 UTC by eheimbuch

## Proposed changes

Add tag overview to repository for git and mercurial. Also show additional information on branches but only for branches overview.
### Your checklist for this pull request

- [ ] PR is well described
- [ ] Related issues linked to PR if existing and labels set
- [ ] Target branch is not master (in most cases develop should bet the target of choice) 
- [ ] Code does not conflict with target branch
- [ ] New code is covered with unit tests
- [ ] CHANGELOG.md updated
- [ ] Definition of Done's fulfilled: [DoD](https://github.com/scm-manager/scm-manager/blob/develop/docs/en/development/definition-of-done.md) // [UI DoD](https://github.com/scm-manager/scm-manager/blob/develop/docs/en/development/ui-dod.md)
- [ ] Documentation updated (only necessary for new features or changed behaviour)

### Checklist for branch merge request (not required for forks)

- [ ] Branch is green/blue on [Jenkins](https://oss.cloudogu.com/jenkins/)
- [ ] Quality Gate passed on [SonarQube](https://sonarcloud.io/organizations/scm-manager/projects)

2020-09-17 20:09 UTC, Pilopa requested changes

2020-09-17 20:09 UTC, Pilopa commented on scm-ui/ui-webapp/src/repos/tags/orderTags.ts
> +export default function orderTags(tags: Tag[]) {
It would be preferable if this function was pure

2020-09-18 06:59 UTC, eheimbuch commented on scm-plugins/scm-hg-plugin/src/main/js/HgTagInformation.tsx
> +        <code>hg update {tag.name}</code>
This state is not possible, since i check earlier if the tag is undefined and return null if so.

2020-09-18 06:59 UTC, eheimbuch commented on scm-plugins/scm-git-plugin/src/main/js/GitTagInformation.tsx
> +          git checkout tags/{tag?.name} -b branch/{tag?.name}
This state is not possible, since i check earlier if the tag is undefined and return null if so.

2020-09-18 06:59 UTC, eheimbuch commented on scm-plugins/scm-git-plugin/src/main/js/GitTagInformation.tsx
> +const GitTagInformation: FC<Props> = ({ tag }) => {
That name would be too specific imho. We could not enhance it.

2020-09-18 07:00 UTC, eheimbuch commented on scm-plugins/scm-hg-plugin/src/main/js/HgTagInformation.tsx
> +const HgTagInformation: FC<Props> = ({ tag }) => {
That name would be too specific imho. We could not enhance it.

2020-09-18 07:05 UTC, eheimbuch commented on scm-ui/ui-types/src/Tags.ts
> +  date: Date;
You are right. I missed this.

2020-09-18 09:16 UTC, Pilopa approved these changes

2020-09-18 09:16 UTC, merged