Feature/fullscreen
scm-manager/scm-manager pull request #1376
Opened 2020-10-14 22:33 UTC by fscholdei

## Proposed changes

Source code of a file (also diff view in PR and editor) can be displayed in full screen view.

### Your checklist for this pull request

- [x] PR is well described
- [x] Related issues linked to PR if existing and labels set
- [x] Target branch is not master (in most cases develop should bet the target of choice) 
- [x] Code does not conflict with target branch
- [x] New code is covered with unit tests
- [x] CHANGELOG.md updated
- [x] Definition of Done's fulfilled: [DoD](https://github.com/scm-manager/scm-manager/blob/develop/docs/en/development/definition-of-done.md) // [UI DoD](https://github.com/scm-manager/scm-manager/blob/develop/docs/en/development/ui-dod.md)
- [x] Documentation updated (only necessary for new features or changed behaviour)

### Checklist for branch merge request (not required for forks)

- [ ] Branch is green/blue on [Jenkins](https://oss.cloudogu.com/jenkins/)
- [ ] Quality Gate passed on [SonarQube](https://sonarcloud.io/organizations/scm-manager/projects)

2020-10-19 10:04 UTC, eheimbuch requested changes

2020-10-19 10:04 UTC, eheimbuch commented on scm-ui/ui-webapp/src/repos/sources/containers/Content.tsx
> +            <OpenInFullscreenButton onClick={this.openModal} />
Why not use the extension point which is right beneath? I know you will need to expose more props to the extension point but it should be okay. Maybe I am missing something. Let's also talk about this.

2020-10-19 10:09 UTC, eheimbuch commented
I discussed your modal layout with UXP and we both think it looks fine. :+1:

2020-10-20 06:33 UTC, fscholdei commented on scm-ui/ui-webapp/src/repos/sources/components/content/SourcecodeViewer.tsx
> +  });
Okay, I was just unsure because my IDE is now asking for an array of all dependencies.

2020-10-20 06:35 UTC, fscholdei commented on scm-ui/ui-webapp/src/repos/sources/components/content/SourcecodeViewer.tsx
> +        });
That may indeed be the case, thanks for the hint 🙈

2020-10-20 08:20 UTC, fscholdei commented on scm-ui/ui-components/src/buttons/OpenInFullscreenButton.tsx
> +    </Button>
Very nice idea!

2020-10-20 10:31 UTC, merged