Feature "Commit Date for Branch"
scm-manager/scm-manager pull request #1439
Opened 2020-11-24 11:07 UTC by pfeuffer

## Proposed changes

Show the date of the last commit for branches and split the branches overview into "active" and "stale" branches depending on their age releative to the default branch.

### Your checklist for this pull request

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] PR is well described
- [x] Related issues linked to PR if existing and labels set
- [x] Target branch is not master (in most cases develop should bet the target of choice) 
- [x] Code does not conflict with target branch
- [x] New code is covered with unit tests
- [x] CHANGELOG.md updated
- [x] Definition of Done's fulfilled: [DoD](https://github.com/scm-manager/scm-manager/blob/develop/docs/en/development/definition-of-done.md) // [UI DoD](https://github.com/scm-manager/scm-manager/blob/develop/docs/en/development/ui-dod.md)
- [x] Documentation updated (only necessary for new features or changed behaviour)

### Checklist for branch merge request (not required for forks)

- [ ] Branch is green/blue on [Jenkins](https://oss.cloudogu.com/jenkins/)
- [ ] Quality Gate passed on [SonarQube](https://sonarcloud.io/organizations/scm-manager/projects)

2020-11-25 16:43 UTC, eheimbuch requested changes

2020-11-25 16:43 UTC, eheimbuch commented on docs/de/user/repo/branches.md
> +nicht 30 Tage älter als derjenige des Default-Branches ist. Alle weiteren Branches sind in der Liste "Stale Branches" zu finden.
```suggestion
Die Branches sind in zwei Listen aufgeteilt: Unter "Aktive Branches" sind Branches aufgelistet, deren letzter Commit
nicht 30 Tage älter als der Stand des Default-Branches ist. Alle älteren Branches sind in der Liste "Stale Branches" zu finden.
```

2020-11-25 16:43 UTC, eheimbuch commented on docs/en/user/repo/branches.md
> +branch are listed in "Active Branches". The other ones can be found in "Stale Branches".
```suggestion
Branches are split into two lists: Branches whose last commits are at most 30 days older than the head of the default
branch are listed in "Active Branches". The older ones can be found in "Stale Branches".
```

2020-11-25 16:43 UTC, eheimbuch commented on scm-core/src/main/java/sonia/scm/repository/api/BranchXDaysOlderThanDefaultStaleComputer.java
> +    if (!branch.isDefaultBranch() && branch.getLastCommitDate().isPresent() && defaultBranch.getLastCommitDate().isPresent()) {
```suggestion
    if (shouldCompute(branch, defaultBranch) {
```

2020-11-25 16:43 UTC, eheimbuch commented on scm-core/src/main/java/sonia/scm/repository/api/BranchXDaysOlderThanDefaultStaleComputer.java
> +    if (!branch.isDefaultBranch() && branch.getLastCommitDate().isPresent() && defaultBranch.getLastCommitDate().isPresent()) {
Wrap your check to increase readability.

2020-11-25 16:43 UTC, eheimbuch commented on scm-core/src/main/java/sonia/scm/repository/spi/BranchesCommand.java
> +    return branches;
In general this is fine but i find it kinda hard to read. I would have filtered for the default branch, initialized the StaleContext with the default branch and afterwards compute the branches within a foreach loop.

But you can leave it that way.

2020-11-25 16:44 UTC, eheimbuch commented
Please mind the code smells which sonarcloud found.

2020-11-25 16:52 UTC, eheimbuch commented
I have not found changes about the branch caching. Does our current caching already work with your changes? Especially the cache invalidation?

2020-11-26 07:29 UTC, pfeuffer commented
> I have not found changes about the branch caching. Does our current caching already work with your changes? Especially the cache invalidation?

The cache is invalidated on every push in the `ClearCacheHook`: https://github.com/scm-manager/scm-manager/blob/develop/scm-core/src/main/java/sonia/scm/repository/api/RepositoryServiceFactory.java#L303

2020-11-26 08:01 UTC, pfeuffer commented
Tried to improve the readability in `BranchesComputer`. Please have a look at it, @eheimbuch

2020-11-26 08:37 UTC, merged