Feature/branch details prs
scm-manager/scm-manager pull request #1888
Opened 2021-12-07 09:28 UTC by eheimbuch

## Proposed changes

Prepare branches overview to show additional branch details.

### Your checklist for this pull request

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

**Contributor**:
- [ ] PR is well described and the description can be used as a commit message on squash
- [ ] Related issues linked to PR if existing and labels set
- [ ] New code is covered with unit tests
- [ ] New ui components are tested inside the storybook (module ui-components only) 
- [ ] [Changelog entry file](https://github.com/scm-manager/changelog#changelog-entry-files) created in `gradle/changelog` or CHANGELOG.md is updated for plugins
- [ ] Feature has been tested with different permissions
- [ ] Documentation updated (only necessary for new features or changed behaviour)

**Reviewer**:
- [ ] The clean code principles are respected ([CleanCode](https://clean-code-developer.com/virtues/))
- [ ] All new code/logic is implemented on the right spot / "Should this be done here?"
- [ ] UI changes fits into the layout
- [ ] The UI views / components are responsive (mobile views)
- [ ] Correct translations are available

### Checklist for branch merge request (not required for forks)

- [ ] Branch is green/blue on [Jenkins](https://oss.cloudogu.com/jenkins/)
- [ ] Quality Gate passed on [SonarQube](https://sonarcloud.io/organizations/scm-manager/projects)

2021-12-07 13:38 UTC, pfeuffer requested changes
First of all, the changes to `ResourceLinks` are not necessary and should be reverted.
Besided I'm missing a changelog file, and I don't like the title of this PR which will get a commit message (and here `Feature/...` isn't nice) and isn't really related to the changes (which are about adding an extension point to the branches table). So, what about "Add extension point to branches overview"?

2021-12-07 13:38 UTC, pfeuffer commented on scm-webapp/src/main/java/sonia/scm/api/v2/resources/ResourceLinks.java
> +  private final Provider<ScmPathInfoStore> scmPathInfoStore;
This whole change is unnecessary. You should use a `Provider` where the resource links are injected.

2021-12-08 07:58 UTC, Pilopa commented
I'm not sure about the SmallLoadingSpinner. Does this have to be in ui-components already ? Is it used in a plugin ? Couldn't it just be in the same file it was extracted from but in its own functional component ?

2021-12-10 07:58 UTC, matthiasthieroff approved these changes
One small issue

2021-12-10 07:58 UTC, matthiasthieroff commented on scm-plugins/scm-hg-plugin/src/test/java/sonia/scm/repository/spi/HgBranchDetailsCommandTest.java
> +    val result = new HgBranchDetailsCommand(cmdContext).execute(branchRequest).getDetails();
Why use `val` instead of `BranchDetails` as in line 63?

2021-12-10 10:05 UTC, merged