Feature/content breaks correctly
scm-manager/scm-manager pull request #1950
Opened 2022-02-11 14:55 UTC by Phil-Ah

## Proposed changes
Enable breaking of content to be fully available on small screens or highly zoomed displays. This should help improve accessibility. 

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. Please ensure the "what" and "why" are explained properly in this description as it will be used as the commit description on squashing your pull request commits. 

### Your checklist for this pull request

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

**Contributor**:
- [x] PR is well described and the description can be used as a commit message on squash
- [ ] Related issues linked to PR if existing and labels set
- [ ] New code is covered with unit tests
- [ ] New ui components are tested inside the storybook (module ui-components only) 
- [ ] [Changelog entry file](https://github.com/scm-manager/changelog#changelog-entry-files) created in `gradle/changelog`
- [ ] Feature has been tested with different permissions
- [ ] Documentation updated (only necessary for new features or changed behaviour)

**Reviewer**:
- [ ] The clean code principles are respected ([CleanCode](https://clean-code-developer.com/virtues/))
- [ ] All new code/logic is implemented on the right spot / "Should this be done here?"
- [ ] UI changes fits into the layout
- [ ] The UI views / components are responsive (mobile views)
- [ ] Correct translations are available

### Checklist for branch merge request (not required for forks)

- [ ] Branch is green/blue on [Jenkins](https://oss.cloudogu.com/jenkins/)
- [ ] Quality Gate passed on [SonarQube](https://sonarcloud.io/organizations/scm-manager/projects)

2022-02-16 00:09 UTC, Pilopa requested changes

2022-02-16 00:09 UTC, Pilopa commented on scm-ui/ui-webapp/src/repos/permissions/components/PermissionsTable.tsx
> +const BreakingPermissionsTable = styled.table`
This styled component is unused.

2022-02-16 00:09 UTC, Pilopa commented on scm-ui/ui-webapp/src/users/components/table/Details.tsx
> +import {Checkbox, DateFromNow, MailLink, createAttributesForTesting, InfoTable} from "@scm-manager/ui-components";
Is prettier not configured ?

2022-02-16 00:19 UTC, Pilopa commented on scm-ui/ui-components/src/forms/AddKeyValueEntryToTableField.tsx
> +const MobileWrapedDiv = styled.div`
Wrapped ?

2022-02-16 00:22 UTC, Pilopa commented on scm-ui/ui-components/src/forms/AddKeyValueEntryToTableField.tsx
> +    & > fieldset {
This selector is dependent on the internal structure of the InputField component. If we would keep the `FullWidthInputField` as a styled component, we could reference it here so no reference to the `fieldset` would be necessary.

2022-02-16 00:23 UTC, Pilopa commented
- [ ] In the storybook story for breadcrumbs with long path names, the copy button is outside the viewport on mobile devices. This might not be a problem in the real-world application but it looks odd that the example breaks

2022-02-16 14:42 UTC, fscholdei submitted a review, later dismissed

2022-02-16 14:42 UTC, fscholdei commented on scm-ui/ui-components/src/table/Table.tsx
> +          return <td className={child.props.className}>{React.cloneElement(child, { ...child.props, columnIndex, row })}</td>;
The styling is applied to the entire column, as shown in the table stories. The child of a td is not affected.

2022-02-17 12:48 UTC, Pilopa approved these changes

2022-02-18 13:48 UTC, merged