Collapse folders with only one child folder
scm-manager/scm-manager pull request #1951
Opened 2022-02-14 13:25 UTC by matthiasthieroff

## Proposed changes

Collapses a folder in code view which only has another folder as its only child. This lets you access a sub-folder which has content directly instead of navigating down the folder tree by clicking every folder separately.

### Your checklist for this pull request

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

**Contributor**:
- [ ] PR is well described and the description can be used as a commit message on squash
- [ ] Related issues linked to PR if existing and labels set
- [ ] New code is covered with unit tests
- [ ] New ui components are tested inside the storybook (module ui-components only) 
- [ ] [Changelog entry file](https://github.com/scm-manager/changelog#changelog-entry-files) created in `gradle/changelog`
- [ ] Feature has been tested with different permissions
- [ ] Documentation updated (only necessary for new features or changed behaviour)

**Reviewer**:
- [ ] The clean code principles are respected ([CleanCode](https://clean-code-developer.com/virtues/))
- [ ] All new code/logic is implemented on the right spot / "Should this be done here?"
- [ ] UI changes fits into the layout
- [ ] The UI views / components are responsive (mobile views)
- [ ] Correct translations are available

### Checklist for branch merge request (not required for forks)

- [ ] Branch is green/blue on [Jenkins](https://oss.cloudogu.com/jenkins/)
- [ ] Quality Gate passed on [SonarQube](https://sonarcloud.io/organizations/scm-manager/projects)

2022-02-14 15:16 UTC, pfeuffer requested changes
Somehow this does not work with HG in some constellations. I have an old copy of the hg repository of SCM-Manager (get it [here](https://next-scm.cloudogu.com/scm/repo/pfeuffer/scm-manager-hg/info)).

Otherwise there are only minor remarks.

2022-02-14 15:16 UTC, pfeuffer commented on scm-webapp/src/test/java/sonia/scm/api/v2/resources/SourceRootResourceTest.java
> -import com.google.inject.util.Providers;
I like the overall cleanup of this class, but somewhere you could add a further test method that checks something like

```java
verify(browseCommandBuilder).setCollapse(true)
```

2022-02-15 06:22 UTC, matthiasthieroff commented on scm-core/src/test/java/sonia/scm/repository/api/BrowserResultCollapserTest.java
> +    assertThat(children.size()).isEqualTo(3);
Unfortunately, I don't got a warning :|

2022-02-15 06:33 UTC, matthiasthieroff commented on scm-core/src/main/java/sonia/scm/repository/api/BrowseCommandBuilder.java
> +        }
Do you have any suggestion for a good method name if you also extract the condition?

2022-02-15 09:12 UTC, pfeuffer commented on scm-core/src/main/java/sonia/scm/repository/api/BrowseCommandBuilder.java
> +        }
I thought of extracting the complete result computation, not only the `if` statement.

Something simple like

```java
result = computeBrowserResult(request);
```

2022-02-15 09:16 UTC, matthiasthieroff commented on scm-core/src/main/java/sonia/scm/repository/api/BrowseCommandBuilder.java
> +        }
Okay, commenting on the if statement was a bit misleading.

2022-02-15 09:59 UTC, merged