Feature/cli
scm-manager/scm-manager pull request #1987
Opened 2022-03-31 07:49 UTC by eheimbuch

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. Please ensure the "what" and "why" are explained properly in this description as it will be used as the commit description on squashing your pull request commits. 

### Your checklist for this pull request

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

**Contributor**:
- [ ] PR is well described and the description can be used as a commit message on squash
- [ ] Related issues linked to PR if existing and labels set
- [ ] New code is covered with unit tests
- [ ] New/updated ui components are tested inside the storybook (module ui-components only) 
- [ ] [Changelog entry file](https://github.com/scm-manager/changelog#changelog-entry-files) created in `gradle/changelog`
- [ ] Feature has been tested with different permissions
- [ ] Documentation updated (only necessary for new features or changed behaviour)

**Reviewer**:
- [ ] The clean code principles are respected ([CleanCode](https://clean-code-developer.com/virtues/))
- [ ] All new code/logic is implemented on the right spot / "Should this be done here?"
- [ ] UI changes fits into the layout
- [ ] The UI views / components are responsive (mobile views)
- [ ] Correct translations are available

### Checklist for branch merge request (not required for forks)

- [ ] Branch is green/blue on [Jenkins](https://oss.cloudogu.com/jenkins/)
- [ ] Quality Gate passed on [SonarQube](https://sonarcloud.io/organizations/scm-manager/projects)

2022-03-31 08:00 UTC, matthiasthieroff commented
I have some remarks on the cli itself:
* If a login fails, the error msg is printed right behind "Password:". I would prefer a new line before the msg.
* A `readme` on how to build is missing or at least the app.go should be located in `pkg/cmd/scm` so that the binary built is `scm` by default.
* Some help texts has some non-translated parts for German language (call the cli w/o parameters): `Missing required subcommand` and `Show this help message and exit.`

2022-04-01 06:15 UTC, eheimbuch commented on scm-webapp/src/main/java/sonia/scm/repository/cli/RepositoryCreateCommand.java
> +  @Pattern(regexp="^svn$|^git$|^hg$")
Use own validation type!

2022-04-01 06:17 UTC, eheimbuch commented on scm-webapp/src/main/java/sonia/scm/repository/cli/RepositoryDeleteCommand.java
> +  private String repository;
Validate input?

2022-04-01 06:19 UTC, eheimbuch commented on scm-webapp/src/main/java/sonia/scm/repository/cli/RepositoryCreateCommand.java
> +  private String repository;
Param label

2022-04-01 06:20 UTC, eheimbuch commented on scm-webapp/src/main/java/sonia/scm/repository/cli/RepositoryDeleteCommand.java
> +  private String repository;
Param label

2022-04-01 06:21 UTC, eheimbuch commented on scm-webapp/src/main/java/sonia/scm/repository/cli/RepositoryModifyCommand.java
> +import com.cronutils.utils.VisibleForTesting;
Wrong import?

2022-04-01 06:21 UTC, eheimbuch commented on scm-webapp/src/main/java/sonia/scm/repository/cli/RepositoryModifyCommand.java
> +  private String repository;
Validation

2022-04-04 05:49 UTC, matthiasthieroff commented
I found a view more minor issues in the cli itself:
* `README.md` line 5: `./app` is the wrong executable name
* The `ping` command does not make much sense, because there are already three explicit states: unreachable (error), not logged in (message), logged in (cli usage and help). I would at least hide `ping` from usage.
* There a few unhandled errors. I would prefer that they are handled or explicitely ignored
* Missing German translations for cli messages
* `scm.go` line 77, 78: I would remove the blank line and the superfluous comment

2022-04-04 06:52 UTC, matthiasthieroff requested changes

2022-04-04 06:52 UTC, matthiasthieroff commented on docs/en/development/cli-guideline.md
> +The repository `type` and `namespace/name` must be set, so these are annotated as parameters.
```suggestion
The repository `type` and `namespace/name` must be set, so they must be annotated as parameters. 
```

2022-04-04 06:52 UTC, matthiasthieroff commented on docs/en/development/cli-guideline.md
> +The other fields like `init` and `description` are optional and are therefore options.
```suggestion
The other fields like `init` and `description` are optional and are therefore annotated as options.
```

2022-04-04 06:52 UTC, matthiasthieroff commented on docs/en/development/cli-guideline.md
> +Commands which returns large texts or much content should allow templating.
```suggestion
Commands which return large texts or much content should allow templating. 
```

2022-04-04 06:52 UTC, matthiasthieroff commented on docs/en/development/cli-guideline.md
> +This can be achieved by using the TemplateRenderer.
```suggestion
This can be achieved by using the TemplateRenderer.
```

2022-04-04 06:52 UTC, matthiasthieroff commented on docs/en/development/cli-guideline.md
> +If you inject the TemplateRenderer you must annotate it as Mixin:
```suggestion
If you inject the TemplateRenderer you must annotate it as a Mixin:
```

2022-04-04 06:52 UTC, matthiasthieroff commented on docs/en/development/cli-guideline.md
> +Besides, "loose" templates you can use a table-like template to render your output.
```suggestion
Besides "loose" templates, you can use a table-like template to render your output. 
```

2022-04-04 06:52 UTC, matthiasthieroff commented on docs/en/development/cli-guideline.md
> +By default, we support english and german translations.
```suggestion
By default, we support English and German translations.
```

2022-04-04 06:52 UTC, matthiasthieroff commented on docs/en/development/cli-guideline.md
> +But you also can you throw the exception directly inside your execution.
```suggestion
However, you also can throw an exception directly inside your execution. 
```

2022-04-04 06:52 UTC, matthiasthieroff commented on docs/en/development/cli-guideline.md
> +  }
```suggestion
```java
  @Inject
  public MyCommand(CommandValidator validator) {
    this.validator = validator;
  }
```

2022-04-04 06:52 UTC, matthiasthieroff commented on docs/en/development/cli-guideline.md
> +```
```suggestion
@Override
public void run() {
  validator.validate();
  ...
}
```
```

2022-04-04 09:22 UTC, matthiasthieroff approved these changes

2022-04-04 10:02 UTC, merged